Region: ${AWS_REGION}

Image:
  Os: ubuntu2204

HeadNode:
  InstanceType: g6.xlarge
  Dcv:
    Enabled: ${ENABLE_DCV}
  Networking:
    SubnetId: ${HEAD_NODE_SUBNET_ID}
    ElasticIp: true
    SecurityGroups:
      - ${HEAD_NODE_SG_ID}
  Ssh:
    KeyName: ${KEY_NAME}
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/AmazonS3FullAccess
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
  LocalStorage:
    RootVolume:
      Size: 120
      VolumeType: gp3

Scheduling:
  Scheduler: slurm
  SlurmSettings:
    ScaledownIdletime: 10
    QueueUpdateStrategy: TERMINATE
  SlurmQueues:
    # High-Performance GPU Queue for training/HPC workloads (H100 GPUs)
    - Name: high-gpu-queue
      Networking:
        SubnetIds:
          - ${COMPUTE_SUBNET_ID}
        SecurityGroups:
          - ${COMPUTE_NODE_SG_ID}
        PlacementGroup:
          Enabled: true
      ComputeSettings:
        LocalStorage:
          RootVolume:
            Size: 120
            VolumeType: gp3
      ComputeResources:
        - Name: high-gpu-nodes
          InstanceType: p5.4xlarge
          MinCount: 0
          MaxCount: 4
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/AmazonS3FullAccess
          - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
    
    # GPU Queue for inference workloads (L4 GPUs)
    - Name: gpu-queue-inference
      Networking:
        SubnetIds:
          - ${COMPUTE_SUBNET_ID}
        SecurityGroups:
          - ${COMPUTE_NODE_SG_ID}
        PlacementGroup:
          Enabled: true
      ComputeSettings:
        LocalStorage:
          RootVolume:
            Size: 120
            VolumeType: gp3
      ComputeResources:
        - Name: gpu-nodes-g6f-l4
          InstanceType: g6f.2xlarge
          MinCount: 0
          MaxCount: 10
    
    # High CPU Queue for compute-intensive workloads
    - Name: cpu-queue-high
      Networking:
        SubnetIds:
          - ${COMPUTE_SUBNET_ID}
        SecurityGroups:
          - ${COMPUTE_NODE_SG_ID}
      ComputeSettings:
        LocalStorage:
          RootVolume:
            Size: 120
            VolumeType: gp3
      ComputeResources:
        - Name: highcpu-nodes
          InstanceType: c7i.16xlarge
          MinCount: 0
          MaxCount: 50
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/AmazonS3FullAccess
          - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
    
    # Default CPU Queue for general workloads
    - Name: cpu-queue-default
      Networking:
        SubnetIds:
          - ${COMPUTE_SUBNET_ID}
        SecurityGroups:
          - ${COMPUTE_NODE_SG_ID}
      ComputeSettings:
        LocalStorage:
          RootVolume:
            Size: 120
            VolumeType: gp3
      ComputeResources:
        - Name: defaultcpu-nodes
          InstanceType: c7i.xlarge
          MinCount: 0
          MaxCount: 50
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/AmazonS3FullAccess
          - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite

SharedStorage:${SHARED_STORAGE_CONFIG}

Monitoring:
  DetailedMonitoring: false
  Logs:
    CloudWatch:
      Enabled: true
      RetentionInDays: 14

Tags:
  - Key: Project
    Value: ParallelCluster
  - Key: ManagedBy
    Value: Terraform
  - Key: Environment
    Value: dev