#!/bin/bash
# Configuration values for SLURM job submission.
# One leading hash ahead of the word SBATCH is not a comment, but two are.
#SBATCH --time=24:00:00 
##SBATCH -x node[110]
#SBATCH --job-name=mutation_processing
#SBATCH -n 1 
#SBATCH -N 1   
##SBATCH --gres=gpu:a100:1
#SBATCH --cpus-per-task=1  
#SBATCH --constraint=cpu-nodes-c7i-4xl
#SBATCH --mem=80gb  
## SBATCH --output /shared/out/ankh-%j.out 

WORKING_DIR="/shared/EvolvePro"

cd $WORKING_DIR 

source ~/.bashrc
conda activate evolvepro 

# Working Directory

python prepare_processing.py
# git pull
